### ISSUE TITLE
[P99+] Multiple segments support

### ISSUE THREAD

**Issue by Jwalksy** [pelmers/gpx-replay#1]
Input:
GPX file with multiple segments such as
```
  <trk>
    <name>Bâle / Huninge / Kembs</name>
    <trkseg>
      ...
     </trkseg>
  </trk>
  <trk>
    <name>Kembs / Mulhouse</name>
    <trkseg>
      ...
     </trkseg>
  </trk>
```

Output:
A merged one on map.

**Comment by pelmers** [comment]
can you share here an example file?

**Comment by Jwalksy** [comment]
[saint-nazaire-to-ajay.txt](https://github.com/pelmers/gpx-replay/files/9693625/saint-nazaire-to-ajay.txt)
I uploaded as .txt here since git comments doesn't support .gpx. It should be easily changed to .gpx by renaming.
Uploading this file in GPX Replay, it only shows the first segment on my side.

**Comment by pelmers** [comment]
<img width="696" alt="Schermafbeelding 2022-10-03 om 08 42 44" src="https://user-images.githubusercontent.com/2406051/193515810-88654886-02b6-4b15-92d4-2ea5bd275901.png">

now there's a checkbox at import time to join all tracks
