### ISSUE TITLE
Feature request: Save user settings without login/registration

### ISSUE THREAD

**Issue by fkroepfl** [pelmers/gpx-replay#16]
Description:
- We propose to implement a feature that allows the web application to remember the parameter settings selected by the user and save them across sessions. This would allow the application to be launched in the user's preferred configuration on subsequent visits, even without requiring login or registration.

Benefits:
- Improved user experience by retaining personalisation.
- Users do not have to repeatedly customise settings, saving time and effort.
- Reduced friction for users who prefer not to set up an account.

Recommended implementation:
- Use browser-based storage solutions such as cookies or local storage to store and retrieve parameter settings.
- Ensure compliance with data protection regulations (e.g. GDPR) by notifying users and offering an opt-out option if required.

Thank you in advance should you consider this improvement!

**Comment by pelmers** [comment]
not in scope

**Comment by fkroepfl** [comment]
Taken note of, even if it's a pity 😉
