### ISSUE TITLE
[REQUEST] Follow Track

### ISSUE THREAD

**Issue by domin80r** [pelmers/gpx-replay#3]
Awesome project!

Request: If the total track is larger than the map area shown, can the moving track pointer be kept in the centre of the map and the map moves? Not sure if that is possible.

Thanks, Dom

**Comment by pelmers** [comment]
Hi Dom! I'm not sure I understand exactly what you mean by moving the map with the point in the center.
Have you tried to use the FollowCam toggle?
If so, specifically how is the behavior you're talking about different from what we do now with follow cam? In this mode we always center the moving point in the view as it travels along the track.

<img width="679" alt="Scherm­afbeelding 2022-11-22 om 09 32 59" src="https://user-images.githubusercontent.com/2406051/203264967-ae41e8b0-c9ae-4cde-8da4-b9cff8129086.png">

**Comment by domin80r** [comment]
Hi Peter, the default of FollowCam is at an angle behind the point. I didn't realise I could move the angle to 90 above it and have it follow. Which is **exactly** what I wanted!

Sorry, this was user error on my part, I'll close the ticket.

Thanks!
